### PR TITLE
Delete Dockerfile.prow and rebuild docker image with latest security updates

### PR DESCRIPTION
**Pull request by jlpadilla**
**Related Issue:**  open-cluster-management/backlog#11041

### Description of changes
- Remove Dockerfile.prow
- Rebuild docker image with latest security updates

### CODE REVIEW

**Comment by mqhackett** [comment]
Waiting for build to succeed. But basically, I read this as our attempt to reduce duplication by levering Dockerfile via Prow?

**Comment by jlpadilla** [comment]
Yes, remove the duplication of Dockerfile.prow and also rebuilds the image to fix CVE.

**Review by mqhackett — APPROVED** [review]

**Pull request merged**
